### ISSUE TITLE
Hello I want to help you (colaborate)

### ISSUE THREAD

**Issue by kopeek** [Indie-Pipeline/indie-blueprint-docs#1]
@ninetailsrabbit I would like to help you with your project, I can try to add improvements to Geometry, other features etc. Could you send me your Discord name so I can add you? I prefer that method of communications :D, Mine is .susdog

**Comment by sempitern0** [comment]
Hey @kopeek thanks your interest in this repository, I don't consider this as a project like so, there are just a bunch of useful stuff that saves me time from repetitive stuff in game dev. You can open a pull request with your improvements and I will review it without problems.

My discord name is the same as in github _(and any other social media)_
